Controllers/ClubController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PhotoPortalWebApp.Interfaces;
using PhotoPortalWebApp.Models;
using PhotoPortalWebApp.ViewModels;

namespace PhotoPortalWebApp.Controllers
{
    public class ClubController : Controller
    {
        private readonly IClubRepository _clubRepository;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly ICloudinaryPhotoService _photoService;

        public ClubController(IClubRepository clubRepository, ICloudinaryPhotoService photoService, IHttpContextAccessor httpContextAccessor)
        {
            _clubRepository = clubRepository;
            _httpContextAccessor = httpContextAccessor;
            _photoService = photoService;
        }

        // GET: Club
        public async Task<IActionResult> Index() 
        {
            IEnumerable<Club> clubs = await _clubRepository.GetAll();
            return View(clubs);
        }

        // GET: Club/Details/5
        public async Task<IActionResult> Details(int id)
        {
            Club club = await _clubRepository.GetByIdAsync(id);
            return View(club);
        }

        // GET: Club/Create
        [Authorize]
        public IActionResult Create()
        {
            string? currentUserId = _httpContextAccessor.HttpContext.User.GetUserId();
            var createClubViewModel = new CreateClubViewModel { AppUserId = currentUserId };
            return View(createClubViewModel);
        }
        
        // POST: Club/Create
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(CreateClubViewModel clubVM)
        {
            if (ModelState.IsValid)
            {
                var result = await _photoService.AddPhotoAsync(clubVM.ProfilePicture);
                var club = new Club
                {
                    Title = clubVM.Title,
                    Description = clubVM.Description,
                    ProfilePictureUrl = result.Url.ToString(),
                    ClubCategory = clubVM.ClubCategory,
                    AppUserId = clubVM.AppUserId,
                    Address = new Address
                    {
                        City = clubVM.Address.City,
                        Street = clubVM.Address.Street,
                        PostalCode = clubVM.Address.PostalCode,
                        Country = clubVM.Address.Country,
                    }
                };
                _clubRepository.Add(club);
                return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError("CreateClubError", "Creation of club failed. Please try again.");
            }
            return View(clubVM);
        }


        // GET: Club/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int id)
        {
            var club = await _clubRepository.GetByIdAsync(id);
            if (club == null) return View("Error");
            var clubVM = new EditClubViewModel
            {
                Title = club.Title,
                Description = club.Description,
                AddressId = club.AddressId,
                Address = club.Address,
                URL = club.ProfilePictureUrl,
                ClubCategory = club.ClubCategory
            };
            return View(clubVM);
        }

        
        // POST: Club/Edit/5
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Edit(int id, EditClubViewModel clubVM)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Failed to edit club");
                return View("Edit", clubVM);
            }
            var userClub = await _clubRepository.GetByIdAsyncNoTracking(id);

            if (userClub != null)
            {
                try
                {
                    await _photoService.DeletePhotoAsync(userClub.ProfilePictureUrl);
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", "Could not delete photo");
                    return View(clubVM);
                }
                var photoResult = await _photoService.AddPhotoAsync(clubVM.ProfilePicture);
                var club = new Club
                {
                    Id = id,
                    Title = clubVM.Title,
                    Description = clubVM.Description,
                    ProfilePictureUrl = photoResult.Url.ToString(),
                    AddressId = clubVM.AddressId,
                    Address = clubVM.Address,
                    ClubCategory = clubVM.ClubCategory
                };

                _clubRepository.Update(club);

                return RedirectToAction("Index");
            }
            else
            {
                return View(clubVM);
            }
        }

        // GET: Club/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int id)
        {
            var clubDetails = await _clubRepository.GetByIdAsync(id);
            if (clubDetails == null) return View("Error");
            return View(clubDetails);
        }

        // POST: Club/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize]
        public async Task<IActionResult> DeleteClub(int id)
        {
            var clubDetails = await _clubRepository.GetByIdAsync(id);
            if (clubDetails == null) return View("Error");

            _clubRepository.Delete(clubDetails);
            return RedirectToAction("Index");
        }
    }
}

Controllers/PhotoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PhotoPortalWebApp.Data;
using PhotoPortalWebApp.Interfaces;
using PhotoPortalWebApp.Models;
using PhotoPortalWebApp.Repositories;
using PhotoPortalWebApp.ViewModels;

namespace PhotoPortalWebApp.Controllers
{
    public class PhotoController : Controller
    {
        private readonly IPhotoRepository _photoRepository;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly ICloudinaryPhotoService _cloudinaryPhotoService;

        public PhotoController(IPhotoRepository photoRepository, IHttpContextAccessor httpContextAccessor, ICloudinaryPhotoService cloudinaryPhotoService)
        {
            _photoRepository = photoRepository;
            _cloudinaryPhotoService = cloudinaryPhotoService;
            _httpContextAccessor = httpContextAccessor;
        }

        // GET: Photo
        public async Task<IActionResult> Index()
        {
            IEnumerable<Photo> photos = await _photoRepository.GetAllAsync();
            return View(photos);
        }

        // GET: Photo/Details/5
        public async Task<IActionResult> Details(int id)
        {
            Photo photo = await _photoRepository.GetByIdAsync(id);

            if (photo == null) return NotFound();

            return View(photo);
        }

        // GET: Photo/Create
        [Authorize]
        public IActionResult Create()
        {
            if (_httpContextAccessor == null)
            {
                throw new ArgumentNullException(nameof(_httpContextAccessor));
            }

            var currentUserId = _httpContextAccessor.HttpContext.User.GetUserId();
            //AppUser currentUser = await _userRepository.GetByIdAsync(currentUserId);
            var PhotoVM = new CreatePhotoViewModel { AppUserId = currentUserId};
            return View(PhotoVM);
        }

        // POST: Photo/Create
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(CreatePhotoViewModel photoVM)
        {
            if (ModelState.IsValid)
            {
                var result = await _cloudinaryPhotoService.AddPhotoAsync(photoVM.Image);
                var photo = new Photo
                {
                    Title = photoVM.Title,
                    Description = photoVM.Description,
                    ImageUrl = result.Url.ToString(),
                    PhotoCategory = photoVM.PhotoCategory,
                    UploadDateTime = DateTime.Now,
                    AppUserId = photoVM.AppUserId,
                };
                await _photoRepository.AddAsync(photo);
                return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError("", "Photo upload failed");
            }
            return View(photoVM);
        }

        // GET: Photo/Edit/5
        [Authorize]
        public async Task<IActionResult> Edit(int id)
        {
            var photo = await _photoRepository.GetByIdAsync(id);
            if (photo == null) return View("Error");
            var photoVM = new EditPhotoViewModel
            {
                Title = photo.Title,
                Description = photo.Description,
                ImageUrl = photo.ImageUrl,
                PhotoCategory = photo.PhotoCategory,
                AppUserId = photo.AppUserId,
            };
            return View(photoVM);
        }

        // POST: Photo/Edit/5
        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Edit(int id, EditPhotoViewModel photoVM)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Failed to edit photo.");
                return View("Edit", photoVM);
            }
            var userPhoto = await _photoRepository.GetByIdAsyncNoTracking(id);

            if (userPhoto != null)
            {
                try
                {
                    await _cloudinaryPhotoService.DeletePhotoAsync(userPhoto.ImageUrl);
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", "Could not delete photo");
                    return View(photoVM);
                }
                var photoResult = await _cloudinaryPhotoService.AddPhotoAsync(photoVM.Image);
                var photo = new Photo
                {
                    Id = id,
                    Title = photoVM.Title,
                    Description = photoVM.Description,
                    ImageUrl = photoResult.Url.ToString(),
                    PhotoCategory = photoVM.PhotoCategory,
                    AppUserId = photoVM.AppUserId,
                };

                _photoRepository.Update(photo);

                return RedirectToAction("Index");
            }
            else
            {
                return View(photoVM);
            }
        }

        // GET: Photo/Delete/5
        [Authorize]
        public async Task<IActionResult> Delete(int id)
        {
            Photo photo = await _photoRepository.GetByIdAsync(id);
            if (photo == null) return View("Error");
            return View(photo);
        }

        // POST: Photo/Delete/5
        [HttpPost, ActionName("Delete")]
        [Authorize]
        public async Task<IActionResult> DeletePhoto(int id)
        {
            Photo photo = await _photoRepository.GetByIdAsync(id);
            if (photo == null) return View("Error");

            _photoRepository.Delete(photo);
            return RedirectToAction("Index");
        }
    }
}

Controllers/UserProfileController.cs
using CloudinaryDotNet.Actions;
using Microsoft.AspNetCore.Mvc;
using PhotoPortalWebApp.Interfaces;
using PhotoPortalWebApp.Models;
using PhotoPortalWebApp.Repositories;
using PhotoPortalWebApp.ViewModels;

namespace PhotoPortalWebApp.Controllers
{
    public class UserProfileController : Controller
    {
        private readonly IUserProfileRepository _userProfileRepository;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private readonly ICloudinaryPhotoService _cloudinaryPhotoService;

        public UserProfileController(IUserProfileRepository userProfileRepository, IHttpContextAccessor httpContextAccessor,
            ICloudinaryPhotoService photoService)
        {
            _userProfileRepository = userProfileRepository;
            _httpContextAccessor = httpContextAccessor;
            _cloudinaryPhotoService = photoService;
        }
        private void MapUserEdit(AppUser user, EditUserProfileViewModel editVM, ImageUploadResult photoResult)
        {
            user.Id = editVM.Id;
            user.FullName = editVM.FullName;
            user.ProfileImageUrl = photoResult.Url.ToString();
        }

        // GET: UserProfile
        public async Task<IActionResult> Index()
        {
            var userPhotos = await _userProfileRepository.GetAllUserPhotos();
            var userClubs = await _userProfileRepository.GetAllUserClubs();
            var userProfileViewModel = new UserProfileViewModel()
            {
                Photos = userPhotos,
                Clubs = userClubs,
            };
            return View(userProfileViewModel);
        }

        // GET: UserProfile/Edit
        public async Task<IActionResult> Edit()
        {
            var currentUserId = _httpContextAccessor.HttpContext.User.GetUserId();
            var user = await _userProfileRepository.GetUserById(currentUserId);
            if (user == null) return View("Error");
            var editUserViewModel = new EditUserProfileViewModel()
            {
                Id = currentUserId,
                FullName = user.FullName,
                ProfileImageUrl = user.ProfileImageUrl,
            };
            return View(editUserViewModel);
        }

        // POST: UserProfile/Edit
        [HttpPost]
        public async Task<IActionResult> Edit(EditUserProfileViewModel editVM)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Failed to edit profile");
                return View("Edit", editVM);
            }

            var user = await _userProfileRepository.GetUserByIdNoTracking(editVM.Id);

            user.FullName = editVM.FullName;
            _userProfileRepository.Update(user);

            if (editVM.ProfileImage == null) 
            {
                return RedirectToAction("Index");
            }

            if (user.ProfileImageUrl == "" || user.ProfileImageUrl == null)
            {
                var photoResult = await _cloudinaryPhotoService.AddPhotoAsync(editVM.ProfileImage);
                MapUserEdit(user, editVM, photoResult);

                _userProfileRepository.Update(user);
                return RedirectToAction("Index");
            }
            else
            {
                try
                {
                    await _cloudinaryPhotoService.DeletePhotoAsync(user.ProfileImageUrl);
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", "Could not delete photo.");
                    return View(editVM);
                }

                var photoResult = await _cloudinaryPhotoService.AddPhotoAsync(editVM.ProfileImage);
                MapUserEdit(user, editVM, photoResult);

                _userProfileRepository.Update(user);
                return RedirectToAction("Index");
            }
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Photo Portal</title>
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    @*<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    @*<link rel="stylesheet" href="~/PhotoPortalWebApp.styles.css" asp-append-version="true" />*@
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="~/img/favicon.png" rel="icon">
    <link href="~/img/apple-touch-icon.png" rel="apple-touch-icon">

    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,600;1,700&family=Inter:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&family=Cardo:ital,wght@0,400;0,700;1,400&display=swap" rel="stylesheet">

    <!-- Vendor CSS Files -->
    <link href="~/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
    <link href="~/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">
    <link href="~/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
    <link href="~/vendor/aos/aos.css" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="~/css/main.css" rel="stylesheet">

    <!-- =======================================================
    * Template Name: PhotoFolio - v1.2.0
    * Template URL: https://bootstrapmade.com/photofolio-bootstrap-photography-website-template/
    * Author: BootstrapMade.com
    * License: https://bootstrapmade.com/license/
    ======================================================== -->

</head>
<body>
    <!-- ======= Header ======= -->
    <header id="header" class="header d-flex align-items-center fixed-top">
        <div class="container-fluid d-flex align-items-center justify-content-between">

            <a asp-area="" asp-controller="Home" asp-action="Index" class="logo d-flex align-items-center  me-auto me-lg-0">
                <!-- Uncomment the line below if you also wish to use an image logo -->
                <!-- <img src="~/img/logo.png" alt=""> -->
                <i class="bi bi-camera"></i>
                <h1>PhotoPortal</h1>
            </a>

            <nav id="navbar" class="navbar">
                <ul>
                    @{
                        var controller = ViewContext?.RouteData?.Values["Controller"]?.ToString();
                    }
                    <li><a asp-area="" asp-controller="Home" asp-action="Index" class="@((@controller == "Home") ? "active" : "")">Home</a></li>
                    <li><a asp-area="" asp-controller="Club" asp-action="Index" class="@((@controller == "Club") ? "active" : "")">Photography Clubs</a></li>
                    <li><a asp-area="" asp-controller="Photo" asp-action="Index" class="@((@controller == "Photo") ? "active" : "")">Gallery</a></li>
                    <li><a>|</a></li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li><a asp-area="" asp-controller="UserProfile" asp-action="Index">My Profile</a></li>
                        <li>
                            <form asp-area="" asp-controller="Account" asp-action="Logout">
                                <button id="logout-button">Logout</button>
                            </form>
                        </li>
                    }
                    else
                    {
                        <li><a asp-area="" asp-controller="Account" asp-action="Login">Login</a></li>
                        <li><a asp-area="" asp-controller="Account" asp-action="Register">Register</a></li>
                    }
                </ul>
            </nav><!-- .navbar -->

            <div class="header-social-links">
                <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
                <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
                <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
            </div>
            <i class="mobile-nav-toggle mobile-nav-show bi bi-list"></i>
            <i class="mobile-nav-toggle mobile-nav-hide d-none bi bi-x"></i>

        </div>
    </header><!-- End Header -->
    
    @RenderBody()

    <!-- ======= Footer ======= -->
    <footer id="footer" class="footer static-bottom" style="max-height:100px">
        <div class="container">
            <div class="copyright">
                &copy; Copyright <strong><span>PhotoFolio</span></strong>. All Rights Reserved
            </div>
            <div class="credits">
                <!-- All the links in the footer should remain intact. -->
                <!-- You can delete the links only if you purchased the pro version. -->
                <!-- Licensing information: https://bootstrapmade.com/license/ -->
                <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/photofolio-bootstrap-photography-website-template/ -->
                Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
            </div>
        </div>
    </footer><!-- End Footer -->

    <a href="#" class="scroll-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    <div id="preloader">
        <div class="line"></div>
    </div>

    <!-- Vendor JS Files -->
    <script src="~/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/vendor/swiper/swiper-bundle.min.js"></script>
    <script src="~/vendor/glightbox/js/glightbox.min.js"></script>
    <script src="~/vendor/aos/aos.js"></script>
    <script src="~/vendor/php-email-form/validate.js"></script>

    <!-- Template Main JS File -->
    <script src="~/js/main.js"></script>
</body>
</html>